# Generated by Django 5.1.4 on 2024-12-14 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_inputlistitem_arrival_price_inputlistitem_sell_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='sell_price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
