# Generated by Django 5.1.4 on 2024-12-23 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_saleitem_sell_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inputlist',
            options={'ordering': ['-created_at'], 'verbose_name': 'Input list', 'verbose_name_plural': 'Input lists'},
        ),
        migrations.AlterModelOptions(
            name='output',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='saleslist',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='amount',
            field=models.FloatField(),
        ),
    ]
