# Generated by Django 5.1.4 on 2024-12-27 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_inputlist_options_alter_output_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inputlist',
            options={'ordering': ['-created_at'], 'verbose_name': 'Mahsulot kirimi ', 'verbose_name_plural': 'Mahsulot kirimlari '},
        ),
        migrations.AlterModelOptions(
            name='inputlistitem',
            options={'verbose_name': 'Mahsulot ', 'verbose_name_plural': 'Mahsulotlar '},
        ),
        migrations.AlterModelOptions(
            name='output',
            options={'ordering': ['-created_at'], 'verbose_name': 'Mahsulot chiqimi ', 'verbose_name_plural': 'Mahsulot chiqimlari '},
        ),
        migrations.AlterModelOptions(
            name='saleitem',
            options={'verbose_name': 'Mahsulot ', 'verbose_name_plural': 'Mahsulotlar '},
        ),
        migrations.AlterModelOptions(
            name='saleslist',
            options={'ordering': ['-created_at'], 'verbose_name': 'Sotuv ', 'verbose_name_plural': 'Sotuvlar '},
        ),
    ]
